include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    # Disable public member API docs rule
    public_member_api_docs: false
    sort_pub_dependencies: false

analyzer:
  errors:
    # Treat missing required params as errors
    missing_required_param: error
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
